### ISSUE TITLE
how to set up a local server

### ISSUE THREAD

**Issue by t-cool** [nlaz/flashcards-for-developers#97]
Hi nlaz.

I'm trying to run the server for flashcard on my macBook.
I started mongod and then did `yarn start`, though I faced with the following error.
Could you give me some advice for this issue?
I'd appreciate your help.

```
$ node --version
v8.11.1

$ mongod --version
db version v4.0.4
build environment:
    distarch: x86_64
    target_arch: x86_64

$ mongod
2019-01-10T20:18:51.173+0900 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-01-10T20:18:51.187+0900 I CONTROL  [initandlisten] MongoDB starting : pid=4392 port=27017 dbpath=/data/db 64-bit host=tcool-2.local
...
2019-01-10T20:18:51.187+0900 I CONTROL  [initandlisten] db version v4.0.4
2019-01-10T20:18:51.187+0900 I CONTROL  [initandlisten] git version: f288a3bdf201007f3693c58e140056adf8b04839
2019-01-10T20:18:51.187+0900 I CONTROL  [initandlisten] allocator: system
2019-01-10T20:18:51.187+0900 I CONTROL  [initandlisten] modules: none
2019-01-10T20:18:51.187+0900 I CONTROL  [initandlisten] build environment:
2019-01-10T20:18:51.187+0900 I CONTROL  [initandlisten]     distarch: x86_64
2019-01-10T20:18:51.187+0900 I CONTROL  [initandlisten]     target_arch: x86_64
2019-01-10T20:18:52.505+0900 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2019-01-10T20:18:52.507+0900 I NETWORK  [initandlisten] waiting for connections on port 27017

$ yarn start
yarn run v1.3.2
$ yarn deploy
$ NODE_ENV=production yarn build && NODE_ENV=production node server/index
$ react-scripts build
Creating an optimized production build...
Compiled successfully.
File sizes after gzip:
  408.76 KB  build/static/js/1.86d47a31.chunk.js
  30.59 KB   build/static/js/main.48d468ba.chunk.js
  4.29 KB    build/static/css/1.922d42f0.chunk.css
  2.98 KB    build/static/css/main.6f67a1c8.chunk.css
  763 B      build/static/js/runtime~main.229c360f.js
...
✨ Starting the server on port 5000
MongoDB connection error { MongoParseError: Invalid connection string
    at parseConnectionString (/Users/t-cool/Desktop/flashcards-for-developers-master/node_modules/mongodb-core/lib/uri_parser.js:412:21)
    at connect (/Users/t-cool/Desktop/flashcards-for-developers-master/node_modules/mongodb/lib/operations/mongo_client_ops.js:180:3)
    at connectOp (/Users/t-cool/Desktop/flashcards-for-developers-master/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)
    at executeOperation (/Users/t-cool/Desktop/flashcards-for-developers-master/node_modules/mongodb/lib/utils.js:420:24)
    at MongoClient.connect (/Users/t-cool/Desktop/flashcards-for-developers-master/node_modules/mongodb/lib/mongo_client.js:168:10)
    at Promise (/Users/t-cool/Desktop/flashcards-for-developers-master/node_modules/mongoose/lib/connection.js:521:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/Users/t-cool/Desktop/flashcards-for-developers-master/node_modules/mongoose/lib/connection.js:518:19)
    at Mongoose.connect (/Users/t-cool/Desktop/flashcards-for-developers-master/node_modules/mongoose/lib/index.js:270:15)
    at module.exports (/Users/t-cool/Desktop/flashcards-for-developers-master/database/index.js:6:12)
    at Object.<anonymous> (/Users/t-cool/Desktop/flashcards-for-developers-master/server/index.js:12:29)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
  name: 'MongoParseError',
  [Symbol(mongoErrorContextSymbol)]: {} }
```

**Comment by nlaz** [comment]
Hi @t-cool from that error message it seems that your database uri environment variable is not set correctly. You have to include the path to your MongoDB connection in order to run the application.

Additionally, for local development you will have more luck running the web and server applications separately using the `yarn web` and `yarn server` commands. I'm going to close this issue. Let me know if you have trouble with getting that to work and feel free to reopen the issue if it continues.

**Comment by t-cool** [comment]
@nlaz 
Thank you for your advice!
I fixed the uri on `config/index.js` and I can run server 
```
module.exports = {
  port: process.env.PORT || 5000,
  database: {
    uri: "mongodb://localhost:27017/test",
```

When I access to `localhost:5000`, I see the following message.  It seems to work successfully for the server part.

```
$ yarn server
yarn run v1.3.2
$ NODE_ENV=development nodemon --watch server --exec 'node server/index'
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/noguchihiroki/Desktop/flashcards-for-developers/server/**/*
[nodemon] starting `node server/index`
✨ Starting the server on port 5000
```
After that, I ran `yarn web` to start its frontend.  When I access to `localhost:3000` to see the app, I face with the following error on the browser.  

```
Error: Please pass either 'apiKey' or 'stripe' to StripeProvider. If you're using 'stripe' but don't have a Stripe instance yet, pass 'null' explicitly.
▶ 24 stack frames were collapsed.
Module../src/index.js
src/index.js:19
  16 | 
  17 | mixpanel.init(config.mixpanelAnalyticsKey);
  18 | 
> 19 | ReactDOM.render(
  20 |   <StripeProvider apiKey={config.stripePublicKey}>
  21 |     <MixpanelProvider mixpanel={mixpanel}>
  22 |       <App />
View compiled
__webpack_require__
/Users/noguchihiroki/Desktop/flashcards-for-developers/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
/Users/noguchihiroki/Desktop/flashcards-for-developers/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
```

Could you give me a hint again to fix this issue?
I'd appreciate your help.

**Comment by nlaz** [comment]
That's definitely a bug. Stripe shouldn't be required to run it locally. You can just remove Stripe on your own to run it locally. We will eventually remove it on our own.

**Comment by t-cool** [comment]
@nlaz 
Could you re-open this issue? 
It seems that I can put the budget after you re-open this issue.
